name: Thanks Reporter
on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })


# name: Thank Contributor
# on: pull_request

# jobs:
#   thank_contributor:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3  

#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v2
#         with:
#           message: |
#                         Thank you for your contribution. We aim to review it within 48 hours!
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
